version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      # user/password: root/example
      MYSQL_ROOT_PASSWORD: example

  mood-tracker:
    image: mood-tracker
    restart: always
    ports:
      - 8081:8080
