version: '3.1'

services:
  mysql-database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: moodtracker

  mood-tracker-api:
    build:
      context: ../build
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "mysql-database"
    ports:
      - 8081:8080
